return {
  require("plugins.autopairs"),
  require("plugins.breadcrumbs"),
  require("plugins.ui"),
  require("plugins.lsp"),
  require("plugins.completion"),
  require("plugins.dap"),
  require("plugins.treesitter"),
  require("plugins.telescope"),
  require("plugins.copilot"),
  require("plugins.folding"),
  require("plugins.surround"),
  require("plugins.git"),
  require("plugins.misc"),
  require("plugins.database"),
}
